#ifndef _SETTINGS_PARAMS_
#define _SETTINGS_PARAMS_
#include <kamek.hpp>
#include <PulsarSystem.hpp>
#include <Config.hpp>

namespace Pulsar {
namespace UI { class SettingsPanel; }
namespace Settings {

class Params {
public:
    static const int pulsarPageCount = 8;
    static const int userPageCount = 0;
    static const int pageCount = pulsarPageCount + userPageCount;

    static const int maxRadioCount = 8; //per page, due to space
    static const int maxScrollerCount = 5; //per page, due to space

    //Pulsar and User
    static u8 radioCount[pageCount];
    static u8 scrollerCount[pageCount];
    static u8 buttonsPerPagePerRow[pageCount][maxRadioCount];
    static u8 optionsPerPagePerScroller[pageCount][maxScrollerCount];

};

//Contains all the settings. 
enum Type {
    SETTINGSTYPE_MISC,
    SETTINGSTYPE_MISC2,
    SETTINGSTYPE_MISC3,
    SETTINGSTYPE_RULES,
    SETTINGSTYPE_RULES2,
    SETTINGSTYPE_ITEM,
    SETTINGSTYPE_KO,
    SETTINGSTYPE_WW,
    SETTINGSTYPE_OTT,
};

//If you want to add settings to your packs, they go in this enum, and GetUserSettingValue should be used to obtain the value of a given setting
enum UserType {
};

}//namespace Settings

//SETTINGS ENUM, for the page, DO NOT FORGET THE +8 for scrollers (see menu settings for example)
//Use these 3 for "u32 setting" in GetSettingValue, the return will be the value of the other enums
enum MiscSettings {
    MISC_RADIO_FASTMENUS = 0,
    MISC_INPUTVIEWER = 1,
    MISC_CHANGEFPS = 2,
    MISC_DEFLICKER = 3,
    MISC_BLUR = 4,
    MISC_RADIO_MUSIC = 5,
    MISC_SCROLL_BOOT = 0 + 8
};

enum Misc2Settings {
    MISC_TRANSMISSION = 0,
    MISC_FOVSCALE = 1,
    MISC_MEGAFOV = 2,
    MISC_ALWAYSDRIFT = 3,
    MISC_BRAKEDRIFT = 4,
    MISC_FALLFAST = 5,
    MISC_CUSTOMCC = 0 + 8,
};

enum Misc3Settings {
    MISC_RADIO_MII = 0,
    MISC_RADIO_SPEEDUP = 1,
    MISC_RADIO_BATTLE = 2,
    MISC_RADIO_BLUES = 3,
    MISC_LUMA = 4,
    MISC_RADIO_SOM = 5,
    MISC_SCROLL_SOM = 0 + 8
};

enum RulesSettings {
    RULES_RADIO_HOSTWINS = 0,
    RULES_ALLOW_MIIHEADS = 1,
    RULES_ALLOW_BDRIFTING = 2,
    RULES_ALLOW_ALWAYSDRIFT = 3,
    RULES_ALLOW_FALLFAST = 4,
    RULES_ALLOW_ULTRAS = 5,
    RULES_RADIO_CC = 1 + 8,
    RULES_SCROLL_GP_RACES = 0 + 8,
};

enum Rules2Settings {
    RULES_MAYHEM_CODES = 0,
    RULES_INVIS_WALLS = 1,
    RULES_VEHICLERESTRICT = 2,
    RULES_CHARRESTRICT = 3,
    RULES_SCROLL_FORCETRANSMISSION = 0 + 8,
    RULES_GAMEMODE = 1 + 8,
};

enum ItemSettings {
    ITEM_ITEMBOXSPAWN = 0,
    ITEM_THUNDERCLOUD = 1,
    ITEM_FLYINGBLOOP = 2,
    ITEM_ALLITEMS = 3,
    ITEM_TCTOGGLE = 4,
};

enum KOSettings {
    KO_ENABLED = 0,
    KO_FINAL = 1,
    KO_KOPERRACE = 0 + 8,
    KO_RACESPERKO = 1 + 8,
};

enum WWSettings {
    WW_GAMEMODE = 0,
    WW_FROOMSTART = 0 + 8,
};

enum OTTSettings {
    OTT_ONLINE = 0,
    OTT_OFFLINE = 1,
    OTT_ALLOWCHANGECOMBO = 2,
    OTT_MUTEPTANDPLAYERS = 3,
};

//MENU SETTINGS
enum MenuSettingFastMenus {
    MENUSETTING_FASTMENUS_DISABLED = 0x0,
    MENUSETTING_FASTMENUS_ENABLED = 0x1
};

enum DKWSettingInputDisplay {
    DKWSETTING_INPUTDISPLAY_DISABLED,
    DKWSETTING_INPUTDISPLAY_ENABLED,
};

enum DKWSettingChangeFPSMode {
    DKWSETTING_FPS_60,
    DKWSETTING_FPS_30,
};

enum DKWSettingDeflicker {
    DKWSETTING_DEFLICKER_DISABLED = 0x0,
    DKWSETTING_DEFLICKER_ENABLED = 0x1
};

enum DKWSettingBlur {
    DKWSETTING_BLUR_DISABLED = 0x0,
    DKWSETTING_BLUR_ENABLED = 0x1
};

enum MenuSettingMusic {
    MENUSETTING_MUSIC_DEFAULT = 0x0,
    MENUSETTING_MUSIC_DISABLE_ALL = 0x1,
    MENUSETTING_MUSIC_DISABLE_RACE = 0x2
};

enum MenuSettingBoot {
    MENUSETTING_BOOT_DISABLED,
    MENUSETTING_BOOT_L1,
    MENUSETTING_BOOT_L2,
    MENUSETTING_BOOT_L3,
    MENUSETTING_BOOT_L4
};

//RACE SETTINGS
enum RaceSettingMII {
    RACESETTING_MII_DISABLED = 0x0,
    RACESETTING_MII_ENABLED = 0x1
};

enum RaceSettingSPEEDUP {
    RACESETTING_SPEEDUP_DISABLED = 0x0,
    RACESETTING_SPEEDUP_ENABLED = 0x1
};

enum RaceSettingBATTLE {
    RACESETTING_BATTLE_GLITCH_DISABLED = 0x0,
    RACESETTING_BATTLE_GLITCH_ENABLED = 0x1
};

enum RaceSettingBLUES {
    RACESETTING_DRAGGABLE_BLUES_DISABLED = 0x0,
    RACESETTING_DRAGGABLE_BLUES_ENABLED = 0x1
};

enum DKWSettingLuma {
    DKWSETTING_LUMA_ENABLED,
    DKWSETTING_LUMA_DISABLED,
};

enum RaceSettingSOM {
    RACESETTING_SOM_LEFT = 0x0,
    RACESETTING_SOM_RIGHT = 0x1,
    RACESETTING_SOM_DISABLED = 0x2
};

enum RaceSettingSOMDigits {
    HOSTSETTING_SOM_DIGITS_0,
    HOSTSETTING_SOM_DIGITS_1,
    HOSTSETTING_SOM_DIGITS_2,
    HOSTSETTING_SOM_DIGITS_3,
};

//HOST SETTINGS
enum HostSettingHAW {
    HOSTSETTING_HOSTWINS_DISABLED,
    HOSTSETTING_HOSTWINS_ENABLED
};

enum HostSettingHostCC {
    HOSTSETTING_CC_NORMAL,
    HOSTSETTING_CC_50,
    HOSTSETTING_CC_REAL100,
    HOSTSETTING_CC_150,
    HOSTSETTING_CC_100,
    HOSTSETTING_CC_400,
    HOSTSETTING_CC_99999,
};

enum HostSettingMiiHeads {
    HOSTSETTING_ALLOW_MIIHEADS_ENABLED,
    HOSTSETTING_ALLOW_MIIHEADS_DISABLED
};

enum HostSettingGPRACES {
    HOSTSETTING_GP_RACES_4,
    HOSTSETTING_GP_RACES_8,
    HOSTSETTING_GP_RACES_12,
    HOSTSETTING_GP_RACES_24,
    HOSTSETTING_GP_RACES_32,
    HOSTSETTING_GP_RACES_64,
    HOSTSETTING_GP_RACES_2,
};

enum DKWSettingAllow150BrakeDrift {
    DKWSETTING_150_BRAKEDRIFT_ON,
    DKWSETTING_150_BRAKEDRIFT_OFF
};

enum DKWSettingAllow150FallFast {
    DKWSETTING_150_FALLFASTON,
    DKWSETTING_150_FALLFASTOFF
};

enum DKWSettingAllowDriftAnywhere {
    DKWSETTING_ALLOW_DANYWHEREON,
    DKWSETTING_ALLOW_DANYWHEREOFF
};

enum DKWSettingUltras {
    DKWSETTING_ULTRAS_ENABLED,
    DKWSETTING_ULTRAS_DISABLED,
};

//KOSETTINGS
enum KOSettingEnabled {
    KOSETTING_DISABLED,
    KOSETTING_ENABLED,
    KOSETTING_LAP_ENABLED,
};
enum KOSettingFINAL {
    KOSETTING_FINAL_DISABLED,
    KOSETTING_FINAL_ALWAYS,
};

enum KOSettingKOPerRace {
    KOSETTING_KOPERRACE_1,
    KOSETTING_KOPERRACE_2,
    KOSETTING_KOPERRACE_3,
    KOSETTING_KOPERRACE_4
};

enum KOSettingRacesPerKO {
    KOSETTING_RACESPERKO_1,
    KOSETTING_RACESPERKO_2,
    KOSETTING_RACESPERKO_3,
    KOSETTING_RACESPERKO_4
};

//DKWSETTINGS1
enum DKWSettingTransmission {
    DKWSETTING_TRANSMISSION_DEFAULT,
    DKWSETTING_TRANSMISSION_ALLINSIDE,
    DKWSETTING_TRANSMISSION_BIKEINSIDE,
    DKWSETTING_TRANSMISSION_ALLOUTSIDE,
};

enum DKWSettingCustomCC {
   DKWSETTING_CUSTOMCC_50,
   DKWSETTING_CUSTOMCC_100,
   DKWSETTING_CUSTOMCC_400,
   DKWSETTING_CUSTOMCC_99999,
};

enum DKWSettingFOVScale {
    DKWSETTING_FOV_DEFAULT,
    DKWSETTING_FOV_16_9,
    DKWSETTING_FOV_4_3,
};

enum DKWSettingBetterMegaFOV {
    DKWSETTING_MEGAFOV_DISABLED,
    DKWSETTING_MEGAFOV_ENABLED,
};

enum DKWSettingBrakeDrift {
    DKWSETTING_BRAKEDRIFT_DISABLED,
    DKWSETTING_BRAKEDRIFT_ENABLED,
};

enum DKWSettingFallFast {
    DKWSETTING_FALLFAST_DISABLED,
    DKWSETTING_FALLFAST_ENABLED
};

enum DKWSettingDriftAnywhere {
    DKWSETTING_DANYWHERE_DISABLED,
    DKWSETTING_DANYWHERE_ENABLED
};

//DKWSETTINGS2
enum DKWSettingMayhemCodes {
    DKWSETTING_MAYHEM_ENABLED,
    DKWSETTING_MAYHEM_DISABLED,
};

enum DKWSettingInvisWalls {
    DKWSETTING_INVISWALLS_ENABLED,
    DKWSETTING_INVISWALLS_DISABLED
};

enum DKWSettingVehicleRestrict {
    DKWSETTING_VEHICLERESTRICT_DEFAULT,
    DKWSETTING_VEHICLERESTRICT_KARTS,
    DKWSETTING_VEHICLERESTRICT_BIKES,
};

enum DKWSettingCharRestrict {
    DKWSETTING_CHARRESTRICT_DEFAULT,
    DKWSETTING_CHARRESTRICT_LIGHT,
    DKWSETTING_CHARRESTRICT_MEDIUM,
    DKWSETTING_CHARRESTRICT_HEAVY,
    DKWSETTING_CHARRESTRICT_PRINCESS,
};

enum DKWSettingForceTransmission {
    DKWSETTING_FORCE_TRANSMISSION_DEFAULT,
    DKWSETTING_FORCE_TRANSMISSION_VANILLA,
    DKWSETTING_FORCE_TRANSMISSION_INSIDEALL,
    DKWSETTING_FORCE_TRANSMISSION_OUTSIDEALL
};

enum DKWSettingGamemode {
    DKWSETTING_GAMEMODE_REGULAR,
    DKWSETTING_GAMEMODE_UNKNOWNITEMS,
    DKWSETTING_GAMEMODE_ITEMRAIN,
    DKWSETTING_GAMEMODE_BUMPERKARTS,
    DKWSETTING_GAMEMODE_RIIBALANCED,
    DKWSETTING_GAMEMODE_MAYHEM,
    DKWSETTING_GAMEMODE_BATTLEROYALE,
};

//ITEM
enum DKWSettingItemBoxSpawn {
    DKWSETTING_ITEMBOX_DEFAULT,
    DKWSETTING_ITEMBOX_FASTSPAWN,
    DKWSETTING_ITEMBOX_INSTANTSPAWN,
    DKWSETTING_ITEMBOX_DISABLED,
};

enum DKWSettingThunderCloud {
    DKWSETTING_THUNDERCLOUD_MEGA,
    DKWSETTING_THUNDERCLOUD_SHRINK,
};

enum DKWSettingFlyingBlooper {
    DKWSETTING_FLYINGBLOOP_FEATHER,
    DKWSETTING_FLYINGBLOOP_BLOOPER
};

enum DKWSettingAllItems {
    DKWSETTING_ALLITEMS_ENABLED,
    DKWSETTING_ALLITEMS_DISABLED
};

enum DKWSettingTCToggle {
    DKWSETTING_TCTOGGLE_DISABLED,
    DKWSETTING_TCTOGGLE_ENABLED
};

//WORLDWIDE
enum DKWSettingWWGamemode {
    DKWSETTING_WWGAMEMODE_REGULAR,
    DKWSETTING_WWGAMEMODE_ITEMRAIN,
    DKWSETTING_WWGAMEMODE_MAYHEM,
};

enum DKWSettingFroomStart {
    DKWSETTING_FROOMSTART_DISABLED,
    DKWSETTING_FROOMSTART_REGULAR,
    DKWSETTING_FROOMSTART_ITEMRAIN,
    DKWSETTING_FROOMSTART_MAYHEM,
};

//UNUSED
enum OTTSettingOnline {
    OTTSETTING_ONLINE_DISABLED,
    OTTSETTING_ONLINE_NORMAL,
    OTTSETTING_ONLINE_FEATHER,
};

enum OTTSettingOffline {
    OTTSETTING_OFFLINE_DISABLED,
    OTTSETTING_OFFLINE_NORMAL,
    OTTSETTING_OFFLINE_FEATHER,
};

enum OTTSettingCombo {
    OTTSETTING_COMBO_DISABLED,
    OTTSETTING_COMBO_ENABLED
};

enum MenuSettingLayout {
    MENUSETTING_LAYOUT_DEFAULT = 0x0,
    MENUSETTING_LAYOUT_ALPHABETICAL = 0x1
};

} //namespace Pulsar


#endif

//SettingParam