#ifndef _SETTINGS_PARAMS_
#define _SETTINGS_PARAMS_
#include <kamek.hpp>
#include <PulsarSystem.hpp>
#include <Config.hpp>

namespace Pulsar {
namespace UI { class SettingsPanel; }
namespace Settings {

class Params {
public:
    static const int pulsarPageCount = 5;
    static const int userPageCount = 5;
    static const int pageCount = pulsarPageCount + userPageCount;

    static const int maxRadioCount = 8; //per page, due to space
    static const int maxScrollerCount = 5; //per page, due to space

    //Pulsar and User
    static u8 radioCount[pageCount];
    static u8 scrollerCount[pageCount];
    static u8 buttonsPerPagePerRow[pageCount][maxRadioCount];
    static u8 optionsPerPagePerScroller[pageCount][maxScrollerCount];

};

//Contains all the settings. 
enum Type {
    SETTINGSTYPE_MENU,
    SETTINGSTYPE_RACE,
    SETTINGSTYPE_HOST,
    SETTINGSTYPE_OTT,
    SETTINGSTYPE_KO,
};

//If you want to add settings to your packs, they go in this enum, and GetUserSettingValue should be used to obtain the value of a given setting
enum UserType {
    SETTINGSTYPE_DKW1,
    SETTINGSTYPE_DKW2,
    SETTINGSTYPE_DKW3,
    SETTINGSTYPE_DKW4,
    SETTINGSTYPE_DKW5,
};

}//namespace Settings

//SETTINGS ENUM, for the page, DO NOT FORGET THE +8 for scrollers (see menu settings for example)
//Use these 3 for "u32 setting" in GetSettingValue, the return will be the value of the other enums
enum MenuSettings {
    SETTINGMENU_RADIO_FASTMENUS = 0,
    SETTINGMENU_RADIO_MUSIC = 1,
    SETTINGMENU_RADIO_LAYOUT = 2,
    SETTINGMENU_SCROLL_BOOT = 0 + 8
};

enum RaceSettings {
    SETTINGRACE_RADIO_MII,
    SETTINGRACE_RADIO_SPEEDUP,
    SETTINGRACE_RADIO_BATTLE,
    SETTINGRACE_RADIO_BLUES,
    SETTINGRACE_RADIO_SOM,
    SETTINGRACE_SCROLL_SOM = 0 + 8
};

enum HostSettings {
    SETTINGHOST_RADIO_HOSTWINS = 0,
    SETTINGHOST_ALLOW_MIIHEADS = 1,
    SETTINGDKW_RANKED_FROOMS = 2,
    SETTINGHOST_RADIO_CC = 1 + 8,
    SETTINGHOST_SCROLL_GP_RACES = 0 + 8,
};

enum OTTSettings {
    SETTINGOTT_ONLINE = 0,
    SETTINGOTT_OFFLINE = 1,
    SETTINGOTT_ALLOWCHANGECOMBO = 2,
    SETTINGOTT_MUTEPTANDPLAYERS = 3,
};

enum KOSettings {
    SETTINGKO_ENABLED = 0,
    SETTINGKO_FINAL = 1,
    SETTINGKO_KOPERRACE = 0 + 8,
    SETTINGKO_RACESPERKO = 1 + 8,
};

enum DKWSettings1 {
    SETTINGDKW_TRANSMISSION = 0,
    SETTINGDKW_CUSTOMCC = 1,
    SETTINGDKW_BRAKEDRIFT = 2,
    SETTINGDKW_FALLFAST = 3,
    SETTINGDKW_ALWAYSDRIFT = 4,
};

enum DKWSettings2 {
    SETTINGDKW_MAYHEM_CODES = 0,
    SETTINGDKW_SNAKING = 1,
    SETTINGDKW_INVIS_WALLS = 2,
    SETTINGDKW_ITEMBOXRESPAWN = 3,
    SETTINGDKW_VEHICLESTATS = 4,
    SETTINGDKW_GAMEMODE = 0 + 8,
};

enum DKWSettings3 {
    SETTINGDKW_ALLOW_BDRIFTING = 0,
    SETTINGDKW_ALLOW_FALLFAST = 1,
    SETTINGDKW_ALLOW_ALWAYSDRIFT = 2,
    SETTINGDKW_ALLOW_ULTRAS = 3,
    SETTINGDKW_VEHICLERESTRICT = 4,
    SETTINGDKW_CHARRESTRICT = 5,
    SETTINGHOST_SCROLL_FORCETRANSMISSION = 0 + 8,
    SETTINGDKW_TRACKS = 1 + 8,
};

enum DKWSettings4 {
    SETTINGDKW_THUNDERCLOUD = 0,
    SETTINGDKW_FLYINGBLOOP = 1,
    SETTINGDKW_ALLITEMS = 2,
    SETTINGDKW_TCTOGGLE = 3,
    SETTINGDKW_ITEMSTATUS = 4,
    SETTINGDKW_BULLETICON = 5,
};

enum DKWSettings5 {
    SETTINGDKW_INPUTVIEWER = 0,
    SETTINGDKW_CHANGEFPS = 1,
    SETTINGDKW_FLICKERBLUR = 2,
    SETTINGDKW_MEGAFOV = 3,
    SETTINGDKW_NOLUMA = 4,
    SETTINGDKW_STARANIM = 5,
    SETTINGDKW_UICOLOUR = 0 + 8,
};

//MENU SETTINGS
enum MenuSettingFastMenus {
    MENUSETTING_FASTMENUS_DISABLED = 0x0,
    MENUSETTING_FASTMENUS_ENABLED = 0x1
};

enum MenuSettingLayout {
    MENUSETTING_LAYOUT_DEFAULT = 0x0,
    MENUSETTING_LAYOUT_ALPHABETICAL = 0x1
};

enum MenuSettingMusic {
    MENUSETTING_MUSIC_DEFAULT = 0x0,
    MENUSETTING_MUSIC_DISABLE_ALL = 0x1,
    MENUSETTING_MUSIC_DISABLE_RACE = 0x2
};

enum MenuSettingBoot {
    MENUSETTING_BOOT_DISABLED,
    MENUSETTING_BOOT_L1,
    MENUSETTING_BOOT_L2,
    MENUSETTING_BOOT_L3,
    MENUSETTING_BOOT_L4
};

//RACE SETTINGS
enum RaceSettingMII {
    RACESETTING_MII_DISABLED = 0x0,
    RACESETTING_MII_ENABLED = 0x1
};

enum RaceSettingSPEEDUP {
    RACESETTING_SPEEDUP_DISABLED = 0x0,
    RACESETTING_SPEEDUP_ENABLED = 0x1
};

enum RaceSettingBATTLE {
    RACESETTING_BATTLE_GLITCH_DISABLED = 0x0,
    RACESETTING_BATTLE_GLITCH_ENABLED = 0x1
};

enum RaceSettingBLUES {
    RACESETTING_DRAGGABLE_BLUES_DISABLED = 0x0,
    RACESETTING_DRAGGABLE_BLUES_ENABLED = 0x1
};

enum DKWSettingBetterMegaFOV {
    DKWSETTING_MEGAFOV_DISABLED,
    DKWSETTING_MEGAFOV_ENABLED,
};

enum DKWSettingNoLuma {
    DKWSETTING_NOLUMA_DISABLED,
    DKWSETTING_NOLUMA_ENABLED,
};

enum DKWSettingStarAnimation {
    DKWSETTING_STARANIM_DISABLED,
    DKWSETTING_STARANIM_ENABLED,
};

enum RaceSettingSOM {
    RACESETTING_SOM_LEFT = 0x0,
    RACESETTING_SOM_RIGHT = 0x1,
    RACESETTING_SOM_DISABLED = 0x2
};

enum RaceSettingSOMDigits {
    HOSTSETTING_SOM_DIGITS_0,
    HOSTSETTING_SOM_DIGITS_1,
    HOSTSETTING_SOM_DIGITS_2,
    HOSTSETTING_SOM_DIGITS_3,
};

//HOST SETTINGS
enum HostSettingHAW {
    HOSTSETTING_HOSTWINS_DISABLED,
    HOSTSETTING_HOSTWINS_ENABLED
};

enum HostSettingHostCC {
    HOSTSETTING_CC_NORMAL,
    HOSTSETTING_CC_50,
    HOSTSETTING_CC_REAL100,
    HOSTSETTING_CC_150,
    HOSTSETTING_CC_100,
    HOSTSETTING_CC_400,
    HOSTSETTING_CC_99999,
};

enum HostSettingMiiHeads {
    HOSTSETTING_ALLOW_MIIHEADS_ENABLED,
    HOSTSETTING_ALLOW_MIIHEADS_DISABLED
};

enum DKWSettingRankedFrooms {
    DKWSETTING_RANKEDFROOMS_DISABLED,
    DKWSETTING_RANKEDFROOMS_ENABLED,
};

enum HostSettingGPRACES {
    HOSTSETTING_GP_RACES_4,
    HOSTSETTING_GP_RACES_8,
    HOSTSETTING_GP_RACES_12,
    HOSTSETTING_GP_RACES_24,
    HOSTSETTING_GP_RACES_32,
    HOSTSETTING_GP_RACES_64,
    HOSTSETTING_GP_RACES_2,
};

//OTTSETTINGS
enum OTTSettingOnline {
    OTTSETTING_ONLINE_DISABLED,
    OTTSETTING_ONLINE_NORMAL,
    OTTSETTING_ONLINE_FEATHER,
};

enum OTTSettingOffline {
    OTTSETTING_OFFLINE_DISABLED,
    OTTSETTING_OFFLINE_NORMAL,
    OTTSETTING_OFFLINE_FEATHER,
};

enum OTTSettingCombo {
    OTTSETTING_COMBO_DISABLED,
    OTTSETTING_COMBO_ENABLED
};

//KOSETTINGS
enum KOSettingEnabled {
    KOSETTING_DISABLED,
    KOSETTING_ENABLED,
};
enum KOSettingFINAL {
    KOSETTING_FINAL_DISABLED,
    KOSETTING_FINAL_ALWAYS,
};

enum KOSettingKOPerRace {
    KOSETTING_KOPERRACE_1,
    KOSETTING_KOPERRACE_2,
    KOSETTING_KOPERRACE_3,
    KOSETTING_KOPERRACE_4
};

enum KOSettingRacesPerKO {
    KOSETTING_RACESPERKO_1,
    KOSETTING_RACESPERKO_2,
    KOSETTING_RACESPERKO_3,
    KOSETTING_RACESPERKO_4
};

//DKWSETTINGS1
enum DKWSettingTransmission {
    DKWSETTING_TRANSMISSION_DEFAULT,
    DKWSETTING_TRANSMISSION_ALLINSIDE,
    DKWSETTING_TRANSMISSION_BIKEINSIDE,
    DKWSETTING_TRANSMISSION_ALLOUTSIDE,
};

enum DKWSettingCustomCC {
   DKWSETTING_CUSTOMCC_50,
   DKWSETTING_CUSTOMCC_100,
   DKWSETTING_CUSTOMCC_400,
   DKWSETTING_CUSTOMCC_99999,
};

enum DKWSettingBrakeDrift {
    DKWSETTING_BRAKEDRIFT_DISABLED,
    DKWSETTING_BRAKEDRIFT_ENABLED,
};

enum DKWSettingFallFast {
    DKWSETTING_FALLFAST_DISABLED,
    DKWSETTING_FALLFAST_ENABLED
};

enum DKWSettingDriftAnywhere {
    DKWSETTING_DANYWHERE_DISABLED,
    DKWSETTING_DANYWHERE_ENABLED
};

enum DKWSettingInputDisplay {
    DKWSETTING_INPUTDISPLAY_DISABLED,
    DKWSETTING_INPUTDISPLAY_ENABLED,
};

enum DKWSettingChangeFPSMode {
    DKWSETTING_FPS_60,
    DKWSETTING_FPS_30,
};

enum DKWSettingFlickerBlur {
    DKWSETTING_FLICKERBLUR_DISABLED = 0x0,
    DKWSETTING_FLICKERBLUR_ENABLED = 0x1
};

//DKWSETTINGS2
enum DKWSettingMayhemCodes {
    DKWSETTING_MAYHEM_ENABLED,
    DKWSETTING_MAYHEM_DISABLED,
};

enum DKWSettingSnaking {
    DKWSETTING_SNAKING_DISABLED,
    DKWSETTING_SNAKING_ENABLED,
};

enum DKWSettingInvisWalls {
    DKWSETTING_INVISWALLS_ENABLED,
    DKWSETTING_INVISWALLS_DISABLED
};

enum DKWSettingItemBoxRespawn {
    DKWSETTING_ITEMBOX_NORMAL,
    DKWSETTING_ITEMBOX_FASTRESPAWN,
    DKWSETTING_ITEMBOX_INSTANTRESPAWN,
};

enum DKWSettingVehicleStats {
    DKWSETTING_STATS_MAYHEM,
    DKWSETTING_STATS_BUMPERKARTS,
    DKWSETTING_STATS_RIIBALANCED,
    DKWSETTING_STATS_VANILLA,
};

enum DKWSettingGamemode {
    DKWSETTING_GAMEMODE_REGULAR,
    DKWSETTING_GAMEMODE_RANDOM,
    DKWSETTING_GAMEMODE_SHELLSHOCK,
    DKWSETTING_GAMEMODE_UNKNOWNITEMS,
    DKWSETTING_GAMEMODE_ITEMRAIN,
    DKWSETTING_GAMEMODE_BATTLEROYALE,
};

//DKWSETTINGS3
enum DKWSettingAllow150BrakeDrift {
    DKWSETTING_150_BRAKEDRIFT_ON,
    DKWSETTING_150_BRAKEDRIFT_OFF
};

enum DKWSettingAllow150FallFast {
    DKWSETTING_150_FALLFASTON,
    DKWSETTING_150_FALLFASTOFF
};

enum DKWSettingAllowDriftAnywhere {
    DKWSETTING_ALLOW_DANYWHEREON,
    DKWSETTING_ALLOW_DANYWHEREOFF
};

enum DKWSettingUltras {
    DKWSETTING_ULTRAS_ENABLED,
    DKWSETTING_ULTRAS_DISABLED,
};

enum DKWSettingVehicleRestrict {
    DKWSETTING_VEHICLERESTRICT_DEFAULT,
    DKWSETTING_VEHICLERESTRICT_KARTS,
    DKWSETTING_VEHICLERESTRICT_BIKES,
};

enum DKWSettingCharRestrict {
    DKWSETTING_CHARRESTRICT_DEFAULT,
    DKWSETTING_CHARRESTRICT_LIGHT,
    DKWSETTING_CHARRESTRICT_MEDIUM,
    DKWSETTING_CHARRESTRICT_HEAVY,
    DKWSETTING_CHARRESTRICT_PRINCESS,
};

enum DKWSettingForceTransmission {
    DKWSETTING_FORCE_TRANSMISSION_DEFAULT,
    DKWSETTING_FORCE_TRANSMISSION_VANILLA,
    DKWSETTING_FORCE_TRANSMISSION_INSIDEALL,
    DKWSETTING_FORCE_TRANSMISSION_OUTSIDEALL
};

enum DKWSettingTrackSelection {
    DKWSETTING_TRACKSELECTION_ALL,
    DKWSETTING_TRACKSELECTION_CTS,
    DKWSETTING_TRACKSELECTION_SITS,
    DKWSETTING_TRACKSELECTION_REGS
};

//DKWSETTINGS4
enum DKWSettingThunderCloud {
    DKWSETTING_THUNDERCLOUD_MEGA,
    DKWSETTING_THUNDERCLOUD_SHRINK,
    DKWSETTING_THUNDERCLOUD_RANDOM,
};

enum DKWSettingFlyingBlooper {
    DKWSETTING_FLYINGBLOOP_FEATHER,
    DKWSETTING_FLYINGBLOOP_BLOOPER
};

enum DKWSettingAllItems {
    DKWSETTING_ALLITEMS_ENABLED,
    DKWSETTING_ALLITEMS_DISABLED
};

enum DKWSettingItemStatus {
    DKWSETTING_ITEMSTATUS_DISABLED,
    DKWSETTING_ITEMSTATUS_ENABLED
};

enum DKWSettingTCToggle {
    DKWSETTING_TCTOGGLE_DISABLED,
    DKWSETTING_TCTOGGLE_ENABLED
};

enum DKWSettingBulletIcon {
    DKWSETTING_BULLETICON_DISABLED,
    DKWSETTING_BULLETICON_ENABLED
};

enum DKWSettingUIColour {
    DKWSETTING_UICOLOUR_RED,
    DKWSETTING_UICOLOUR_ORANGE,
    DKWSETTING_UICOLOUR_GREEN,
    DKWSETTING_UICOLOUR_BLUE,
    DKWSETTING_UICOLOUR_PURPLE,
    DKWSETTING_UICOLOUR_PINK,
};
}
//namespace Pulsar



#endif

//SettingParam